### ISSUE TITLE
Add Support For reCAPTCHA v2.0

### ISSUE THREAD

**Issue by davidklebanoff** [jaicab/responsive-reCAPTCHA#3]
Support for reCAPTCHA v2.0 would be nice.

**Comment by jaicab** [comment]
I'm working on a new version, this is on my todo list :)

**Comment by Bodge-IT** [comment]
I'll wait for this!  Amazing Given Google's push for mobile friendly sites that their own products are so mobile unfriendly!

**Comment by jaicab** [comment]
Bad news. reCAPTCHA 2.0 **doesn't have a custom theme option** but only [`light` and `dark` versions](https://developers.google.com/recaptcha/docs/display#render_param).

I have been trying every possible way of doing this but there isn't any and probably never will. The current version creates an `iframe` so I can't override the CSS due to cross-origin policies.
I have been talking with some people at Google who talked with other people at Google and the answer is no, due to safety issues, there won't be an option to customise the theme like in version 1.0.

Support on v1.0 is possible because of the flexibility in the HTML and CSS with the custom theme option. So I will be updating v1.0 with a modular, updated approach using Sass. Sorry guys.

**Comment by davidklebanoff** [comment]
How disappointing on Google's part. Thank you for your efforts.

**Comment by Bodge-IT** [comment]
< div class="g-recaptcha" data-theme="light" data-sitekey="XXXXXXXXXXXXX" >{iframe}< /div>

CSS:
.g-recaptcha {
transform: scale(0.77);
transform-origin: 0 0
}

Works for me:
Curtesy https://www.geekgoddess.com/how-to-resize-the-google-nocaptcha-recaptcha/

**Comment by jaicab** [comment]
Thanks for that solution @Bodge-IT, seems it is as good as it's going to get.
Since it is just a hack and not a real complete solution (the emerging windows are still bigger than the viewport) I will not include it as an official solution but I will definitely reference to this issue for people looking for the 2.0 support.
